steps:
  # 1단계 => docker-compose -f docker-compose.prod.yaml build
  - name: docker/compose:1.29.0
    args:
      - -f
      - class/deploy-with-docker/backend/docker-compose.prod.yaml
      - build

    # 2단계 => docker-compose -f docker-compose.prod.yaml push
  - name: docker/compose:1.29.0
    args:
      - -f
      - class/deploy-with-docker/backend/docker-compose.prod.yaml
      - push

    # 3단계 => kubectl set image deployment/backend-nestjs mybackend-nestjs-sha256-1=asia.gcr.io/norse-avatar-358105/mybackend-nestjs:2.1
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/backend-nestjs
      - mybackend-nestjs-sha256-1=asia.gcr.io/norse-avatar-358105/mybackend-nestjs:2.2
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=backend-cluster-1
