version: "3.7"

services:
  # 도커 컴퓨터 이름
  my-backend:
    # 빌드
    build:
      # 도커 파일의 위치
      context: .
      # 도커 파일의 이름
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  my-database:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - 27017:27017
